### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by nonlooped** [Smaug6739/discord-template#2]
```
┌💁  NAME @ PCNAME in 📁  PROJECT on 🌿  master •26 ⌀3 ✗
└❯ yarn dev
yarn run v1.22.11
$ rm -rf ./dist && tsc && yarn start
$ node dist/main
Command loaded: avatar
Event loaded: interactionCreate
Event loaded: ready
Logged in as Bot#0000!
TypeError: Cannot read property 'name' of undefined
    at default_1.<anonymous> (/home/PCNAME/Work/PROJECT/dist/events/interactionCreate.js:45:58)
    at Generator.next (<anonymous>)
    at /home/PCNAME/Work/PROJECT/dist/events/interactionCreate.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/PCNAME/Work/PROJECT/dist/events/interactionCreate.js:4:12)
    at default_1.run (/home/PCNAME/Work/PROJECT/dist/events/interactionCreate.js:18:16)
    at Client.<anonymous> (/home/PCNAME/Work/PROJECT/dist/main.js:89:58)
    at Client.emit (node:events:394:28)
    at InteractionCreateAction.handle (/home/PCNAME/Work/PROJECT/node_modules/discord.js/src/client/actions/InteractionCreate.js:66:12)
    at Object.module.exports [as INTERACTION_CREATE] (/home/PCNAME/Work/PROJECT/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
```

**Comment by Smaug6739** [comment]
Thank you for the report. This bug has just been corrected.  You can clone the repo and compile the code.  (the dist folder is not yet up to date on the repo)
